/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ContactService.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type AddressDto = {
  /** @nullable */
  type: string | null;
  /** @nullable */
  poBox: string | null;
  /** @nullable */
  extendedAddress: string | null;
  /** @nullable */
  streetAddress: string | null;
  /** @nullable */
  locality: string | null;
  /** @nullable */
  region: string | null;
  /** @nullable */
  postalCode: string | null;
  /** @nullable */
  country: string | null;
} | null;
