/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ContactService.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LanguageDto } from './languageDto';
import type { OrganizationDto } from './organizationDto';
import type { AddressDto } from './addressDto';
import type { TelephoneDto } from './telephoneDto';
import type { EmailDto } from './emailDto';
import type { GeographyDto } from './geographyDto';
import type { PublicKeyDto } from './publicKeyDto';
import type { UrlDto } from './urlDto';

export interface CreateVCardRequest {
  language: LanguageDto;
  organization: OrganizationDto;
  address: AddressDto;
  /** @nullable */
  telephones: TelephoneDto[] | null;
  email: EmailDto;
  geography: GeographyDto;
  publicKey: PublicKeyDto;
  /** @nullable */
  timezone: string | null;
  url: UrlDto;
}
