/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ContactService.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */

export * from './addressDto';
export * from './createVCardRequest';
export * from './emailDto';
export * from './geographyDto';
export * from './languageDto';
export * from './organizationDto';
export * from './product';
export * from './publicKeyDto';
export * from './searchContactsParams';
export * from './telephoneDto';
export * from './updateVCardRequest';
export * from './urlDto';
export * from './user';
export * from './vCardDto';
export * from './validationProblemDetails';
export * from './validationProblemDetailsErrors';
export * from './weatherForecast';