/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ContactService.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type PublicKeyDto = {
  /** @nullable */
  type: string | null;
  /** @nullable */
  valueType: string | null;
  /** @nullable */
  uri: string | null;
} | null;
