/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ContactService.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TelephoneDto {
  /** @nullable */
  id: string | null;
  /** @nullable */
  value: string | null;
  /** @nullable */
  valueType: string | null;
  /** @nullable */
  type: string[] | null;
  /** @nullable */
  preference: number | null;
  /** @nullable */
  extension: string | null;
}
