/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ContactService.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  id: number;
  name: string;
  email: string;
  createdAt: string;
}
