/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ContactService.ApiService | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  Product
} from '../../model';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class ProductModuleService {
  private readonly http = inject(HttpClient);
 getApiProducts<TData = null>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiProducts<TData = null>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiProducts<TData = null>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiProducts<TData = null>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/products`,options
    );
  }
 postApiProducts<TData = null>(product: Product, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiProducts<TData = null>(product: Product, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiProducts<TData = null>(product: Product, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiProducts<TData = null>(
    product: Product, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/products`,
      product,options
    );
  }
 getApiProductsId<TData = null>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiProductsId<TData = null>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiProductsId<TData = null>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiProductsId<TData = null>(
    id: number, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/products/${id}`,options
    );
  }
 putApiProductsId<TData = null>(id: number,
    product: Product, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 putApiProductsId<TData = null>(id: number,
    product: Product, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 putApiProductsId<TData = null>(id: number,
    product: Product, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  putApiProductsId<TData = null>(
    id: number,
    product: Product, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.put<TData>(
      `/api/products/${id}`,
      product,options
    );
  }
 deleteApiProductsId<TData = null>(id: number, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteApiProductsId<TData = null>(id: number, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteApiProductsId<TData = null>(id: number, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteApiProductsId<TData = null>(
    id: number, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(
      `/api/products/${id}`,options
    );
  }
};

export type GetApiProductsClientResult = never;
export type PostApiProductsClientResult = never;
export type GetApiProductsIdClientResult = never;
export type PutApiProductsIdClientResult = never;
export type DeleteApiProductsIdClientResult = never;
